In [2]:
import numpy as np
import matplotlib.pyplot as py

In [3]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==== Zomato sales analysis ==== ")
print("\n Sales data shape", sales_data.shape)
print("\n Sample data for 1st 3 restaurant:\n", sales_data[:3]) # select first 3 rows
print("\n Sample data for all restaurant except 2024 data:\n", sales_data[:, :4])     #select all rows but not 4th coulmn
print("\n Sample data for all restaurant (withou id):\n", sales_data[:, 1:])  #select all rows and start with column 1
print("\n Sample data for 1st 3 restaurant (without id):\n", sales_data[:3, 1:])  #select first 3 rows without their id(column)

==== Zomato sales analysis ==== 

 Sales data shape (5, 5)

 Sample data for 1st 3 restaurant:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

 Sample data for all restaurant except 2024 data:
 [[     1 150000 180000 220000]
 [     2 120000 140000 160000]
 [     3 200000 230000 260000]
 [     4 180000 210000 240000]
 [     5 160000 185000 205000]]

 Sample data for all restaurant (withou id):
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]

 Sample data for 1st 3 restaurant (without id):
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]]
