Reverse an array without using loops.

In [12]:
import numpy as np 

arr = np.array([10, 20, 30, 40, 50])
print("Reversed array: ", arr[::-1])        #using slicing method

print("Reversed array: ", np.flip(arr))   #using flip method


matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Reversed matrix: ", np.flip(matrix))

print("Reverse rows only: ", np.flip(matrix, axis=0))
print("Reverse only columns: ", np.flip(matrix, axis=1))

print("reversed matrix", matrix[::-1][:, ::-1]) # reverse rows and columns

Reversed array:  [50 40 30 20 10]
Reversed array:  [50 40 30 20 10]
Reversed matrix:  [[9 8 7]
 [6 5 4]
 [3 2 1]]
Reverse rows only:  [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reverse only columns:  [[3 2 1]
 [6 5 4]
 [9 8 7]]
reversed matrix [[9 8 7]
 [6 5 4]
 [3 2 1]]
