Reverse an array without using loops.

In [2]:
import numpy as np

In [15]:
 

arr = np.array([10, 20, 30, 40, 50])
print("Reversed array: ", arr[::-1])        #using slicing method

print("Reversed array: ", np.flip(arr))   #using flip method


matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Reversed matrix: ", np.flip(matrix))

print("Reverse rows only: ", np.flip(matrix, axis=0))
print("Reverse only columns: ", np.flip(matrix, axis=1))

print("reversed matrix", matrix[::-1][:, ::-1]) # reverse rows and columns

Reversed array:  [50 40 30 20 10]
Reversed array:  [50 40 30 20 10]
Reversed matrix:  [[9 8 7]
 [6 5 4]
 [3 2 1]]
Reverse rows only:  [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reverse only columns:  [[3 2 1]
 [6 5 4]
 [9 8 7]]
reversed matrix [[9 8 7]
 [6 5 4]
 [3 2 1]]


Find duplicate values in an array.

In [5]:
#unique() method
arr = np.array([1, 2, 3, 2, 4, 5, 1, 6])

unique, counts = np.unique(arr, return_counts=True)

duplicates = unique[ counts > 1]
print("\nDuplicate values:", duplicates)

#using loops
duplicates = []

for num in arr:
    if list(arr).count(num) > 1 and num not in duplicates:
        duplicates.append(int(num))

print("\nDuplicates: ", duplicates)


#Count Duplicate Occurrences in a NumPy Array

arr2 = np.array([1, 2, 3, 2, 4, 5, 1, 1, 3, 7])


unique, counts = np.unique(arr2, return_counts=True)

max_counts = np.max(counts)
most_repeated = unique[counts==max_counts]

min_counts = np.min(counts)
least_repeated = unique[counts==min_counts]

print("\nMost repeated value(s):", most_repeated)
print("Occurs:", max_counts, "times")

print("\nLeast repeated value(s):", least_repeated)
print("Occurs:", min_counts, "time(s)")

for value, count in zip(unique, counts):
    if count > 1:
        print(value, "occurs", count, "times")


Duplicate values: [1 2]

Duplicates:  [1, 2]

Most repeated value(s): [1]
Occurs: 3 times

Least repeated value(s): [4 5 7]
Occurs: 1 time(s)
1 occurs 3 times
2 occurs 2 times
3 occurs 2 times
